version: '3.4'
services:
  php:
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      # Switch remote_host to 127.0.0.1 for Linux.
      # Switch remote_enable to 0 to disable xDebug within the container.
      XDEBUG_CONFIG: "remote_enable=0"
      COMPOSER_MEMORY_LIMIT: -1
